# Generated by Django 5.0.7 on 2026-08-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_systemannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemannouncement',
            name='target_audience',
            field=models.CharField(choices=[('all', 'Tous les utilisateurs'), ('owners', 'Propriétaires uniquement')], default='all', max_length=20),
        ),
    ]
