# Generated by Django 5.0.7 on 2026-08-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_systemannouncement_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='teams_override',
            field=models.PositiveIntegerField(blank=True, help_text="Accorde une limite personnalisée d'équipes si spécifié.", null=True),
        ),
    ]
