# Generated by Django 5.0.7 on 2026-08-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_workspace_types_and_personal_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='workspace_type',
            field=models.CharField(choices=[('company', 'Structure'), ('personal', 'Personnel')], default='company', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='audience',
            field=models.CharField(choices=[('company', 'Structure'), ('personal', 'Personnel')], default='company', max_length=20),
        ),
    ]
