# Generated by Django 5.0.7 on 2026-07-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_task', 'Nouvelle tâche'), ('comment', 'Commentaire'), ('report_approved', 'Report accepté'), ('report_rejected', 'Report refusé'), ('new_assignment', 'Nouvelle assignation'), ('task_completed', 'Tâche terminée'), ('subscription_reminder', 'Rappel d’abonnement'), ('payment_succeeded', 'Paiement réussi'), ('payment_failed', 'Paiement échoué'), ('subscription_suspended', 'Abonnement suspendu')], max_length=50),
        ),
    ]
