# Generated by Django 5.0.7 on 2026-07-29 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
        ('tasks', '0006_task_estimated_hours_tasktemplate_estimated_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignments_enabled', models.BooleanField(default=True)),
                ('comments_enabled', models.BooleanField(default=True)),
                ('task_reminders_enabled', models.BooleanField(default=True)),
                ('overdue_alerts_enabled', models.BooleanField(default=True)),
                ('daily_digest_enabled', models.BooleanField(default=True)),
                ('subscription_alerts_enabled', models.BooleanField(default=True)),
                ('reminder_days_before', models.PositiveSmallIntegerField(default=2)),
                ('digest_hour', models.PositiveSmallIntegerField(default=8)),
                ('last_digest_sent_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_task', 'Nouvelle tâche'), ('comment', 'Commentaire'), ('report_approved', 'Report accepté'), ('report_rejected', 'Report refusé'), ('new_assignment', 'Nouvelle assignation'), ('task_completed', 'Tâche terminée'), ('subscription_reminder', 'Rappel d’abonnement'), ('payment_succeeded', 'Paiement réussi'), ('payment_failed', 'Paiement échoué'), ('subscription_suspended', 'Abonnement suspendu'), ('task_due_soon', 'Échéance proche'), ('task_overdue', 'Tâche en retard'), ('daily_digest', 'Résumé quotidien')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('recipient', 'dedupe_key'), name='unique_notification_dedupe_per_recipient'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
