from django.urls import path
from .views import (
    TaskListCreateView,
    TaskDetailView,
    TaskHistoryListView,
    my_tasks,
    assigned_tasks,
    daily_focus,
    TaskCommentListCreateView,
    TaskCommentDetailView,
    TaskAttachmentListCreateView,
    TaskAttachmentDetailView,
    download_attachment,
    duplicate_task,
    restore_task,
    TaskTemplateListCreateView,
    TaskTemplateDetailView,
    instantiate_template,
    save_task_as_template,
    bulk_task_action,
    workload_planning,
    TaskReportListCreateView,
    TaskReportDetailView,
    my_reports,
    pending_reports,
    export_tasks_excel
)

urlpatterns = [
    path('templates/', TaskTemplateListCreateView.as_view(), name='task_template_list'),
    path('templates/<int:id>/', TaskTemplateDetailView.as_view(), name='task_template_detail'),
    path('templates/<int:template_id>/instantiate/', instantiate_template, name='task_template_instantiate'),
    path('bulk/', bulk_task_action, name='task_bulk_action'),
    path('workload/', workload_planning, name='task_workload'),
    path('export/', export_tasks_excel, name='export_tasks_excel'),
    path('', TaskListCreateView.as_view(), name='task_list_create'),
    path('<int:id>/', TaskDetailView.as_view(), name='task_detail'),
    path('<int:task_id>/duplicate/', duplicate_task, name='task_duplicate'),
    path('<int:task_id>/restore/', restore_task, name='task_restore'),
    path('<int:task_id>/save-template/', save_task_as_template, name='task_save_template'),
    path('<int:task_id>/history/', TaskHistoryListView.as_view(), name='task_history'),
    path('<int:task_id>/comments/', TaskCommentListCreateView.as_view(), name='task_comments'),
    path('<int:task_id>/comments/<int:id>/', TaskCommentDetailView.as_view(), name='task_comment_detail'),
    path('<int:task_id>/attachments/', TaskAttachmentListCreateView.as_view(), name='task_attachments'),
    path('<int:task_id>/attachments/<int:id>/', TaskAttachmentDetailView.as_view(), name='task_attachment_detail'),
    path('<int:task_id>/attachments/<int:attachment_id>/download/', download_attachment, name='task_attachment_download'),
    path('<int:task_id>/reports/', TaskReportListCreateView.as_view(), name='task_reports'),
    path('<int:task_id>/reports/<int:id>/', TaskReportDetailView.as_view(), name='task_report_detail'),
    path('my/', my_tasks, name='my_tasks'),
    path('assigned/', assigned_tasks, name='assigned_tasks'),
    path('daily-focus/', daily_focus, name='daily_focus'),
    path('reports/my/', my_reports, name='my_reports'),
    path('reports/pending/', pending_reports, name='pending_reports'),
]
