# Generated by Django 5.0.7 on 2026-07-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weekly_capacity_hours',
            field=models.PositiveSmallIntegerField(default=40),
        ),
    ]
