# Generated by Django 5.0.7 on 2026-07-31 10:31

from django.db import migrations

def convert_administrators_to_managers(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(role='administrator').update(role='manager')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_weekly_capacity_hours'),
    ]

    operations = [
        migrations.RunPython(convert_administrators_to_managers, migrations.RunPython.noop),
    ]
