# Generated by Django 5.0.7 on 2026-08-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_preserve_audit_logs_when_user_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
