# Generated by Django 5.0.7 on 2026-08-18 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_alter_company_workspace_type_and_more'),
        ('users', '0010_user_legal_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauditlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_audit_logs', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Administrateur de la structure'), ('manager', 'Responsable'), ('employee', 'Collaborateur')], default='employee', max_length=20),
        ),
    ]
