# Generated by Django 5.0.7 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userauditlog_company_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Administrateur de la structure'), ('manager', 'Manager'), ('employee', 'Collaborateur')], default='employee', max_length=20),
        ),
    ]
