# Generated by Django 5.0.7 on 2026-07-27 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['company'], name='teams_company_0f0023_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['leader'], name='teams_leader__81dccf_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['is_active'], name='teams_is_acti_dd3222_idx'),
        ),
    ]
