# Generated by Django 5.0.7 on 2026-07-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_next_occurrence_task_recurrence_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
    ]
