# Generated by Django 5.0.7 on 2026-08-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_estimated_hours_tasktemplate_estimated_hours'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tasktemplate',
            name='unique_task_template_name_per_company',
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='is_shared',
            field=models.BooleanField(default=True, help_text='True if shared with company, False if personal to creator'),
        ),
    ]
