# Generated by Django 5.0.7 on 2026-08-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_completion_approvals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('on_hold', 'En pause'), ('deferred', 'Reportée'), ('completed', 'Terminée')], default='todo', max_length=20),
        ),
    ]
