# Generated by Django 5.0.7 on 2026-08-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='parent_comment',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='replies',
                to='tasks.taskcomment',
            ),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['parent_comment'], name='task_comment_parent_idx'),
        ),
    ]
